name: act
channels:
  - defaults
dependencies:
  - python=3.14
  - wget=1.21.4
  - scipy=1.18.1
  - matplotlib=3.11.2
  - pandas=3.0.6
  - pylint=4.0.8
  - autopep8=2.3.2
  - numpy=2.5.3
  - requests=2.34.2
  - flake8=7.3.0
  - pip
  - pytest
  - pip:
      - jax==0.10.2
      - antlr4-python3-runtime==4.9.2
      - nanobind==2.8.0
